### ISSUE TITLE
Backoff configuration may not guarantee the max time between respawns when workers die?

### ISSUE THREAD

**Issue by frankLife** [doxout/recluster#31]
I have been studying the recluster source code recently.It's a great module to control node process.But I have some questions wiht the `backoff` configuration.

There are two files here:
	
index.js: 	

	var path = require('path');
	var recluster = require('recluster');

	var opt = {
		respawn: 0.5
		,
		backoff: 2
	}
	var cluster = recluster(path.join(__dirname,'server.js'),opt);

	cluster.run();
	
server.js:

	var http = require('http');

	
	var s = http.createServer(function(req, res) {
    	var params = req.url.split('/').slice(1);
    	setTimeout(function() { 
        	res.writeHead(200);
        	res.end("hello world\n");
    	}, params[0] || 1);
	});

	s.listen(8000);

	setTimeout(function() {
    	throw new Error("Unclean exit!");
	}, 500);

 I have done `node index.js` some times ,the result will show in the terminal:

![result](http://gtms04.alicdn.com/tps/i4/TB192PEIVXXXXXFaXXXkd9iRVXX-695-672.png)

I find that the respawn time was increasing from 0 to 6293ms(6s).

But the repository README says: 

> opt.backoff

> Maximum respawn time (reached via exponential backoff). Set to 0 or undefined to disable exponential backoff.

I look up the part about backoff in source [code](https://github.com/doxout/recluster/blob/master/index.js#L129-L132).Here time is the `fork` timeout . 

But as mentioned above,let backoff is set 2s, the actual result (2959、4854) exceed `backoff` configuration. 

According the source code, as long as setting the `backoff`,it will invoke [delayedDecreaseBackoff](https://github.com/doxout/recluster/blob/master/index.js#L77-L87) and  respwan time will be divided by 2 in a backoff time later.Before that the respawn time would be multiplied by 2.

But this `exponential backoff` seems like not to guarantee the maximum time between respawns when workers die or I can't make sence of this logic. 

Would you talk about how this design of logic run :)

**Comment by spion** [comment]
recluster maintains optrespawn, a badly named internal variable that keeps the current respawn delay

When a worker dies, we runs workerReplace to replace the worker. At the beginning, in workerReplace we fist [cap the respawn delay to not be greater than the `backoff` option](https://github.com/doxout/recluster/blob/master/index.js#L117)

```js
optrespawn = Math.min(optrespawn, opt.backoff);
```

then [we calculate the next moment](https://github.com/doxout/recluster/blob/master/index.js#L119) that a worker is allowed to respawn, based on the time of the previous respawn plus the respawn delay. 

Of course, that moment cannot be in the past. If the last respawn was hours ago, we need to make sure that the next one will be at least `now` via `Math.max`

```js
nextSpawn = Math.max(now, lastSpawn + optrespawn * 1000)
```

Then we can [calculate the delay of the timer that will respawn the process](https://github.com/doxout/recluster/blob/master/index.js#L120). If the last respawn was indeed ages ago, the next one will happen immediately (`now - now`)

```js
time = nextSpawn - now;
```

Then we can [update the moment of the last spawn](https://github.com/doxout/recluster/blob/master/index.js#L121) for next time

```js
lastSpawn = nextSpawn;
```

Once everything is calculated, we [multiply the current delay by two](https://github.com/doxout/recluster/blob/master/index.js#L125) (it will be capped the next time a respawn happens, so we need not worry about it overshooting) and [run a timer to reset it back](https://github.com/doxout/recluster/blob/master/index.js#L126) via `delayedDecreaseBackoff`

`delayedDecreaseBackoff` (better name: `debouncedDecreaseBackoff`) is a debounced function in the sense of lodash's _.debounce. Its effect is applied `opt.backoff` seconds after its last called, but if called again sooner then that, it will [reset the timer](https://github.com/doxout/recluster/blob/master/index.js#L78-L79). 

The timer is set to the maximum possible delay (opt.backoff) to ensure that the backoff is not decreased if respawns keep happening at intervals shorter than `opt.backoff`. Once the delay hits maximum, it will be kept at that maximum (1) as long as worker respawns are requested, within `opt.backoff` seconds or less. 

If respawn requests stop happening, `delayedDecreaseBackoff` will have a chance to execute and [decrease the current delay by half](https://github.com/doxout/recluster/blob/master/index.js#L81). It ensures that the [delay is not smaller than the minimum](https://github.com/doxout/recluster/blob/master/index.js#L82-L83). Otherwise, if its larger,it schedules itself again (it needs to be decreased further)

Example: Given opt.respawn = 1s, opt.backoff = 10s, we should get something like this if workers keep dying:

1 -> 2 -> 4 -> 8 -> 10 -> 10 -> 10 -> ...

Once workers stop dying, the delay will start decreasing gradually by 1/2 every `opt.backoff` seconds:

10 -> 5 -> 2.5 -> 1.25 -> 1 (timer stops)

I'm not sure whats going on in your case. Since the current delay is always capped before being used and displayed, I don't have an idea where the bug might be

(1): well, it will oscillate between max and 1/2 max. if we add just a few more milliseconds to `opt.backoff` then we can ensure that the delay stays at `max`

**Comment by frankLife** [comment]
It's a great detailed explanation. I totally understand the `debouncedDecreaseBackoff (delayedDecreaseBackoff)` function. 

In this case, I find out the reason why the respawn time exceed `backoff` is that when the workers dies immediatly, the `lastSpawn` will be assign the calculated value and the `optrepsawn` will be multiplied by 2. the same process will run many times in few time.Finally ,It will resuilt in: 

1. optrespawn time will be set max value(`backoff`)
2. the lastSpawn is based on the last lastSpawn but last lastSpawn process may not finish,So the interval time will accumulate more and more.

When I set the time of the server  error timeout is 5000 instead of 500 and  the number of workers is 1 instead of 4 or error time of 10000、 workers of 2 , the result will be right.

Maybe this particular condition(server dies too fast) will trigger this result.

Can we add
 
      	if(opt.backoff) {
            nextSpawn = Math.min(opt.backoff * 1000 + now,nextSpawn);
        }
after 

        var nextSpawn = Math.max(now, lastSpawn + optrespawn * 1000);
        
to ensure the time between respawns not to exceed `backoff`?

**Comment by spion** [comment]
I see what you mean - if a second worker happens to die, the next killed worker will be delayed even more.

But thats the correct behavior, isn't it? Otherwise, if 16 workers die in a row, there will be a flood of 16 respawns in a row, which is precisely what we want to avoid...

**Comment by frankLife** [comment]
Yes,I think the I make sence of what happen. I mistaked the `time` meaning in log.You really help me out of this understanding of problem.

Thank you ;)
